commit 0cbe3e00d820a2022d220d0790c0e85eb96de3d1
Author: Cherry Mui <cherryyz@google.com>
Date:   Mon Feb 7 12:00:04 2022 -0500

    runtime: fix an error message in TestCrashDumpsAllThreads
    
    Change-Id: I04962c836fd448378b8bf071ba848f3b24253dce
    Reviewed-on: https://go-review.googlesource.com/c/go/+/384159
    Trust: Cherry Mui <cherryyz@google.com>
    Reviewed-by: Ian Lance Taylor <iant@golang.org>
    Run-TryBot: Cherry Mui <cherryyz@google.com>
    TryBot-Result: Gopher Robot <gobot@golang.org>
---
 src/runtime/crash_unix_test.go | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/runtime/crash_unix_test.go b/src/runtime/crash_unix_test.go
index 1eb10f9b60..a218205af4 100644
--- a/src/runtime/crash_unix_test.go
+++ b/src/runtime/crash_unix_test.go
@@ -132,7 +132,7 @@ func TestCrashDumpsAllThreads(t *testing.T) {
 	out := outbuf.Bytes()
 	n := bytes.Count(out, []byte("main.crashDumpsAllThreadsLoop("))
 	if n != 4 {
-		t.Errorf("found %d instances of main.loop; expected 4", n)
+		t.Errorf("found %d instances of main.crashDumpsAllThreadsLoop; expected 4", n)
 		t.Logf("%s", out)
 	}
 }
